import type { Signature } from '../types.js';

export const authOnly: Signature = {
  type: 'auth-only',
  routes: {
    login: 6,
    signin: 6,
    signup: 6,
    register: 6,
    logout: 4,
    'forgot-password': 5,
    'reset-password': 5,
    verify: 4,
    auth: 4,
    profile: 3,
    account: 2,
  },
  elements: {
    'sign in': 5,
    'log in': 5,
    'sign up': 5,
    register: 5,
    'create account': 5,
    'forgot password': 5,
    'reset password': 5,
    password: 2,
    email: 1,
  },
  deps: {
    'next-auth': 5,
    '@auth/core': 5,
    clerk: 5,
    '@clerk/nextjs': 5,
    auth0: 5,
    '@auth0/nextjs-auth0': 5,
    '@supabase/auth-helpers-nextjs': 5,
    'firebase-auth': 5,
    'firebase/auth': 5,
    lucia: 5,
    'lucia-auth': 5,
  },
  schema: {
    user: 3,
    users: 3,
    session: 3,
    sessions: 3,
    account: 2,
    verification: 3,
  },
};
