import type { Signature } from '../types.js';

export const booking: Signature = {
  type: 'booking',
  routes: {
    booking: 6,
    bookings: 6,
    book: 6,
    reserve: 5,
    reservation: 6,
    reservations: 6,
    reschedule: 4,
    availability: 5,
    listing: 5,
    listings: 5,
    appointment: 6,
    appointments: 6,
    schedule: 4,
    calendar: 3,
    stay: 3,
    stays: 3,
    room: 2,
    rooms: 2,
  },
  elements: {
    'book now': 6,
    'reserve now': 5,
    'check in': 4,
    'check out': 4,
    'select dates': 4,
    'confirm booking': 5,
    availability: 4,
    'per night': 3,
    guests: 3,
    'date range': 3,
  },
  deps: {
    fullcalendar: 6,
    '@fullcalendar/core': 6,
    '@fullcalendar/react': 6,
    calendly: 5,
    'react-day-picker': 4,
    'react-calendar': 4,
    'date-fns': 2,
    'mapbox-gl': 3,
    leaflet: 3,
    'react-leaflet': 3,
    'airbnb-js-shims': 5,
  },
  schema: {
    reservation: 6,
    reservations: 5,
    booking: 6,
    bookings: 5,
    listing: 6,
    listings: 5,
    appointment: 6,
    appointments: 5,
    slot: 4,
    slots: 4,
    availability: 4,
    host: 4,
    guest: 3,
    property: 3,
    stay: 3,
    room: 3,
  },
};
