import type { Signature } from '../types.js';

export const content: Signature = {
  type: 'content',
  routes: {
    articles: 5,
    article: 5,
    blog: 6,
    post: 4,
    posts: 4,
    read: 4,
    author: 3,
    authors: 3,
    tag: 3,
    tags: 3,
    topic: 3,
    topics: 3,
    category: 3,
    rss: 3,
    feed: 2,
    newsletter: 4,
    search: 2,
  },
  elements: {
    'read more': 4,
    'read article': 4,
    subscribe: 3,
    'newsletter signup': 5,
    'share article': 3,
    'estimated reading time': 4,
    'by author': 3,
    'published on': 3,
  },
  deps: {
    contentful: 6,
    '@contentful/rich-text-react-renderer': 5,
    sanity: 6,
    '@sanity/client': 6,
    'next-sanity': 6,
    ghost: 5,
    '@tryghost/content-api': 6,
    'gray-matter': 4,
    'remark': 3,
    'remark-gfm': 3,
    'rehype': 3,
    'mdx-bundler': 5,
    '@next/mdx': 5,
    'next-mdx-remote': 5,
    prismic: 5,
    '@prismicio/client': 5,
    strapi: 5,
  },
  schema: {
    post: 4,
    posts: 4,
    article: 5,
    articles: 4,
    author: 4,
    category: 3,
    tag: 3,
    comment: 2,
  },
};
