import type { Signature } from '../types.js';

export const crm: Signature = {
  type: 'crm',
  routes: {
    contacts: 6,
    contact: 5,
    leads: 6,
    lead: 5,
    deals: 6,
    deal: 5,
    pipeline: 6,
    pipelines: 5,
    accounts: 4,
    account: 3,
    opportunities: 6,
    opportunity: 5,
    tasks: 3,
    task: 3,
    reports: 3,
    activities: 4,
  },
  elements: {
    'add contact': 5,
    'create deal': 5,
    'assign to': 3,
    'log activity': 4,
    'next step': 3,
    'close deal': 5,
    'move to': 3,
    pipeline: 3,
    'follow up': 4,
  },
  deps: {
    '@hubspot/api-client': 6,
    'salesforce-jsforce': 6,
    jsforce: 6,
    'pipedrive': 6,
    '@sendgrid/mail': 3,
    mailgun: 2,
  },
  schema: {
    contact: 6,
    contacts: 5,
    lead: 6,
    leads: 5,
    deal: 6,
    deals: 5,
    opportunity: 6,
    opportunities: 5,
    account: 4,
    pipeline: 5,
    stage: 4,
    activity: 4,
    task: 3,
  },
};
