import type { Signature } from '../types.js';

export const ecommerce: Signature = {
  type: 'ecommerce',
  routes: {
    cart: 5,
    checkout: 8,
    product: 4,
    products: 4,
    category: 2,
    categories: 2,
    orders: 3,
    order: 3,
    shop: 3,
    store: 3,
    collection: 2,
    collections: 2,
    wishlist: 2,
  },
  elements: {
    'add to cart': 5,
    'add to bag': 5,
    'buy now': 5,
    checkout: 4,
    quantity: 2,
    price: 1,
    sku: 3,
    'place order': 5,
    cart: 2,
    'in stock': 2,
  },
  deps: {
    stripe: 6,
    '@stripe/stripe-js': 6,
    '@stripe/react-stripe-js': 6,
    shopify: 8,
    '@shopify/hydrogen': 8,
    '@shopify/polaris': 6,
    'commerce.js': 6,
    '@commerce/core': 6,
    medusa: 6,
    '@medusajs/medusa': 6,
    'use-shopping-cart': 5,
    braintree: 5,
    'braintree-web': 5,
    paypal: 4,
    '@paypal/react-paypal-js': 5,
  },
  schema: {
    product: 6,
    products: 5,
    order: 6,
    orders: 5,
    orderitem: 5,
    cart: 5,
    cartitem: 4,
    invoice: 3,
    customer: 3,
    inventory: 3,
    sku: 3,
    payment: 4,
  },
};
