import type { Signature } from '../types.js';

export const saas: Signature = {
  type: 'saas',
  routes: {
    dashboard: 6,
    settings: 5,
    billing: 6,
    subscription: 5,
    subscriptions: 5,
    onboarding: 5,
    workspace: 5,
    workspaces: 5,
    team: 4,
    teams: 4,
    members: 4,
    invites: 4,
    integrations: 4,
    usage: 3,
    api: 2,
    app: 2,
  },
  elements: {
    'invite team': 4,
    'create workspace': 5,
    'upgrade plan': 5,
    'start trial': 5,
    'connect integration': 4,
    'api key': 4,
    'manage billing': 5,
    plan: 3,
    seats: 4,
  },
  deps: {
    'next-auth': 4,
    '@auth/core': 4,
    clerk: 5,
    '@clerk/nextjs': 5,
    '@clerk/clerk-react': 5,
    supabase: 3,
    '@supabase/supabase-js': 3,
    '@supabase/auth-helpers-nextjs': 4,
    stripe: 4,
    '@stripe/stripe-js': 4,
    auth0: 5,
    '@auth0/nextjs-auth0': 5,
    posthog: 3,
    'posthog-js': 3,
    launchdarkly: 3,
    'launchdarkly-react-client-sdk': 4,
    sentry: 2,
    '@sentry/nextjs': 3,
  },
  schema: {
    workspace: 6,
    workspaces: 5,
    subscription: 6,
    subscriptions: 5,
    plan: 5,
    user: 3,
    users: 3,
    team: 4,
    teams: 4,
    membership: 4,
    invite: 4,
    apikey: 4,
    apitoken: 4,
    organization: 4,
    org: 3,
  },
};
