import type { Signature } from '../types.js';

export const social: Signature = {
  type: 'social',
  routes: {
    feed: 6,
    post: 5,
    posts: 5,
    profile: 4,
    profiles: 4,
    friends: 5,
    followers: 5,
    following: 5,
    messages: 5,
    message: 4,
    chat: 4,
    chats: 4,
    notifications: 4,
    timeline: 5,
    comments: 4,
    likes: 4,
    explore: 4,
    groups: 3,
    community: 3,
  },
  elements: {
    like: 3,
    comment: 3,
    share: 3,
    follow: 4,
    unfollow: 4,
    'send message': 4,
    post: 2,
    repost: 4,
    'add friend': 5,
    retweet: 5,
    mention: 3,
  },
  deps: {
    'socket.io': 4,
    'socket.io-client': 4,
    'stream-chat-react': 6,
    'getstream.io': 5,
    pusher: 4,
    'pusher-js': 4,
    emoji: 2,
    'emoji-mart': 3,
  },
  schema: {
    post: 6,
    posts: 5,
    comment: 5,
    comments: 4,
    like: 4,
    likes: 3,
    follow: 5,
    follows: 5,
    friend: 4,
    message: 4,
    notification: 3,
    reaction: 4,
    profile: 3,
  },
};
